# Generated by Django 2.2.7 on 2020-01-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeaconModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('eddy_namespace', models.CharField(max_length=200, verbose_name='Eddystone namespace')),
            ],
            options={
                'verbose_name': 'Beacon',
                'verbose_name_plural': 'Beacons',
            },
        ),
    ]
