# Generated by Django 2.2.7 on 2020-01-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watchpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('hour', models.TimeField(auto_now=True)),
                ('status', models.CharField(max_length=10)),
                ('obs', models.TextField(blank=True, null=True)),
                ('watchpost_fk', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='watchpost.WatchpostModel', verbose_name='Monitoramento')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
