# Generated by Django 2.2.7 on 2020-01-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20200113_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmodel',
            name='status',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
