# Generated by Django 2.2.7 on 2020-01-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway_beacon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaybeaconmodel',
            name='name',
            field=models.CharField(default='Beacon', max_length=50),
            preserve_default=False,
        ),
    ]
