# Generated by Django 2.2.7 on 2020-01-08 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('beacon', '0001_initial'),
        ('gateway_beacon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchpostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('start_hour', models.TimeField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_hour', models.TimeField(blank=True, null=True)),
                ('rssi', models.FloatField(blank=True, help_text='Não mexer', null=True, verbose_name='Indicador de Intensidade de Sinal Recebido')),
                ('obs', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Invativo')], max_length=1)),
                ('last_update', models.DateTimeField(blank=True, help_text='Não mexer', null=True)),
                ('beacon', models.OneToOneField(help_text='Não mexer', on_delete=django.db.models.deletion.DO_NOTHING, to='beacon.BeaconModel')),
                ('gateway_beacon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gateway_beacon.GatewayBeaconModel')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleModel')),
            ],
            options={
                'verbose_name': 'Monitoramento',
                'verbose_name_plural': 'Monitoramenros',
            },
        ),
    ]
