# Generated by Django 2.2.7 on 2020-01-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_veacon', '0001_initial'),
        ('watchpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchpostmodel',
            name='user_veacon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user_veacon.UserVeaconModel'),
            preserve_default=False,
        ),
    ]
