# Generated by Django 2.2.7 on 2020-01-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchpost', '0002_watchpostmodel_user_veacon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchpostmodel',
            name='beacon',
            field=models.ForeignKey(help_text='Não mexer', on_delete=django.db.models.deletion.DO_NOTHING, to='beacon.BeaconModel'),
        ),
        migrations.AlterField(
            model_name='watchpostmodel',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleModel'),
        ),
    ]
