# Generated by Django 2.2.7 on 2020-02-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchpost', '0003_auto_20200113_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchpostmodel',
            name='rssi',
        ),
        migrations.AddField(
            model_name='watchpostmodel',
            name='rssi_max',
            field=models.FloatField(blank=True, help_text='RSSI máximo da primeira bateria de scanner', null=True, verbose_name='RSSI máximo'),
        ),
        migrations.AddField(
            model_name='watchpostmodel',
            name='rssi_min',
            field=models.FloatField(blank=True, help_text='RSSI mínimo da primeira bateria de scanner', null=True, verbose_name='RSSI mínimo'),
        ),
    ]
